"""added new column Employees.email_address

Revision ID: 1411e5e5172c
Revises: 3f32939ca94f
Create Date: 2022-04-20 21:20:48.025262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1411e5e5172c'
down_revision = '3f32939ca94f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_address', sa.String(length=120), nullable=True))
        batch_op.drop_constraint('uq_employees_email', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_employees_email_address'), ['email_address'])
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_employees_email_address'), type_='unique')
        batch_op.create_unique_constraint('uq_employees_email', ['email'])
        batch_op.drop_column('email_address')

    # ### end Alembic commands ###
